/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexcion.Conectar;
import Datos.Clientes;
import Datos.Productos;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class CrearPedidos extends javax.swing.JDialog {

    Conectar CT = new Conectar("dbPractica", "usrUTN", "12345");
    private DefaultTableModel lineas;
    private int contLineas;

    public CrearPedidos(java.awt.Frame parent, boolean modal) throws ClassNotFoundException, SQLException {
        super(parent, modal);
        initComponents();
        obtenerClientes();
        obtenerProductos();
        CargarClientes();
        CargarProductos();

        lineas = new DefaultTableModel();

        lineas.addColumn("Linea");
        lineas.addColumn("Codigo");
        lineas.addColumn("Descripcion");
        lineas.addColumn("Cantidad");
        lineas.addColumn("Precio");
        lineas.addColumn("Total");
    }

    public ArrayList<Clientes> obtenerClientes() throws SQLException {

        ResultSet datos = CT.select("*", "\"schPractica\".\"cliente\"", "");
        ArrayList<Clientes> clientes = new ArrayList();
        while (datos.next()) {

            Clientes cli = new Clientes(datos.getString("descripcion"), datos.getString("codigo"));
            clientes.add(cli);

        }

        return clientes;

    }

    public void CargarClientes() throws SQLException {
        for (int x = 0; x < obtenerClientes().size(); x++) {
            ComBoxListaClientes.addItem(obtenerClientes().get(x).getNombre());
        }
    }

    public ArrayList<Productos> obtenerProductos() throws SQLException {
        ResultSet datos = CT.select("*", "\"schPractica\".\"articulo\"", "");
        ArrayList<Productos> productos = new ArrayList();
        while (datos.next()) {
            Productos pro = new Productos(datos.getString("descripcion"), datos.getString("codigo"), datos.getString("precio"));
            productos.add(pro);
        }
        return productos;

    }

    public void CargarProductos() throws SQLException {
        for (int x = 0; x < obtenerProductos().size(); x++) {
            ComBoxListaProductos.addItem(obtenerProductos().get(x).getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComBoxListaClientes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLineas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ComBoxListaProductos = new javax.swing.JComboBox();
        btnInsertar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CLIENTE:");

        ComBoxListaClientes.setToolTipText("");
        ComBoxListaClientes.setFocusable(false);
        ComBoxListaClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComBoxListaClientesItemStateChanged(evt);
            }
        });

        tblLineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLineas);

        jLabel2.setText("PRODUCTO:");

        ComBoxListaProductos.setToolTipText("");
        ComBoxListaProductos.setFocusable(false);
        ComBoxListaProductos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComBoxListaProductosItemStateChanged(evt);
            }
        });

        btnInsertar.setText("INSERTAR");
        btnInsertar.setFocusable(false);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        jLabel3.setText("CANTIDAD:");

        txtCantidad.setText("0");

        btnProcesar.setText("PROCESAR PEDIDO");

        jLabel4.setText("DE 0 DISPONIBLES");

        jLabel5.setText("CODIGO:");

        jLabel6.setText("--------");

        jLabel7.setText("DIRECCIÓN:");

        jLabel8.setText("-----");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("PEDIDO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("00000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComBoxListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertar)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComBoxListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(125, 125, 125)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProcesar)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ComBoxListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComBoxListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnProcesar)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            contLineas++;
            ResultSet datos = CT.select("precio", "\"schPractica\".articulo",
                    "where codigo='" + obtenerProductos().get(ComBoxListaProductos.getSelectedIndex()).getCodigo() + "'");
            Object[] valores = {contLineas, obtenerProductos().get(ComBoxListaProductos.getSelectedIndex()).getCodigo(),
                obtenerProductos().get(ComBoxListaProductos.getSelectedIndex()).getDescripcion(), txtCantidad.getText()};
            lineas.addRow(valores);

            tblLineas.setModel(lineas);
        } catch (SQLException ex) {
            Logger.getLogger(CrearPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtCantidad.setText(null);

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void ComBoxListaProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComBoxListaProductosItemStateChanged

        try {
            ResultSet datos = CT.select("*", "\"schPractica\".\"articulo\"",
                    "where codigo='" + obtenerProductos().get(ComBoxListaProductos.getSelectedIndex()).getCodigo() + "'");
            while (datos.next()) {
                jLabel4.setText("DE " + datos.getString("existencia") + " DISPONIBLES");
            }

        } catch (SQLException ex) {
            Logger.getLogger(CrearPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComBoxListaProductosItemStateChanged

    private void ComBoxListaClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComBoxListaClientesItemStateChanged

        try {

            ResultSet datos = CT.select("*", "\"schPractica\".\"cliente\"",
                    "where codigo='" + obtenerClientes().get(ComBoxListaClientes.getSelectedIndex()).getCodigo() + "'");

            while (datos.next()) {

                jLabel6.setText(datos.getString("codigo"));
                jLabel8.setText(datos.getString("direccion"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(CrearPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ComBoxListaClientesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearPedidos dialog = null;
                try {
                    dialog = new CrearPedidos(new javax.swing.JFrame(), true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CrearPedidos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CrearPedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComBoxListaClientes;
    private javax.swing.JComboBox ComBoxListaProductos;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLineas;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
