/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazProyectoMascotaFeliz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import proyectomascotafeliz.ProcesosCitas;
import javax.swing.table.DefaultTableModel;
import proyectomascotafeliz.archivo;

/**
 *
 * @author Ronald
 */
public class ConsultasConsulta extends javax.swing.JFrame {

    private archivo archivo = new archivo();
    private DefaultTableModel tablaconsultas;
    private DefaultTableModel datosconsulta;
    ProcesosCitas conexioncitas;

    /**
     * Creates new form ConsultasConsulta
     */
    public ConsultasConsulta() {
        tablaconsultas = new DefaultTableModel();
        archivo.leer();
        try {
            this.conexioncitas = new ProcesosCitas(archivo.getBase(), archivo.getUser(), archivo.getPassword());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cargarConsultas();

    }

    public void cargarConsultas() {
        tablaconsultas.addColumn("Codigo");
        tablaconsultas.addColumn("Codigo Cita");
        tablaconsultas.addColumn("Fecha Consulta");

        ResultSet datos = conexioncitas.select("*", "\"schProyecto\".\"consulta\"", "");

        try {
            while (datos.next()) {
                String[] valores = {datos.getString("cod"), datos.getString("cod_cita"), datos.getString("fecha_consulta")};
                tablaconsultas.addRow(valores);
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
        tablaConsultas.setModel(tablaconsultas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDatosDeconsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaConsultas.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tablaConsultas.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tablaConsultas.getTableHeader().setReorderingAllowed(false);
        tablaConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaConsultas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 443, 134));

        tablaDatosDeconsulta.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tablaDatosDeconsulta.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tablaDatosDeconsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaDatosDeconsulta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 346, 1223, 180));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 115, 323, 21));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Consultas efectuadas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Datos consulta ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/reortesConsultas.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/reortesConsultas2.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Cerrar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Cerrar2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 530, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 4, 1250, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarDatos() {
        ResultSet datos = conexioncitas.select4((String) tablaConsultas.getValueAt(tablaConsultas.getSelectedRow(), 0));

        try {
            while (datos.next()) {
                String[] valores = {datos.getString("cod_mascota"), datos.getString("nombre_mascota"), datos.getString("cod_enfermedad"),
                    datos.getString("nombre_enfermedad"), datos.getString("fecha_diagnostico"), datos.getString("notas"), datos.getString("cod_vacuna"),
                    datos.getString("nombre_vacuna"), datos.getString("fecha_aplicacion"), datos.getString("fecha_proxima_aplicacion")};
                datosconsulta.addRow(valores);
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
        tablaDatosDeconsulta.setModel(datosconsulta);
    }
    private void tablaConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConsultasMouseClicked
        // TODO add your handling code here:
        datosconsulta = new DefaultTableModel();
        datosconsulta.addColumn("Cod Mascota");
        datosconsulta.addColumn("Mascota");
        datosconsulta.addColumn("Cod Enfermedad");
        datosconsulta.addColumn("Enfermedad");
        datosconsulta.addColumn("Diagnostico");
        datosconsulta.addColumn("Notas");
        datosconsulta.addColumn("Cod Vacuna");
        datosconsulta.addColumn("Vacuna");
        datosconsulta.addColumn("Aplicación");
        datosconsulta.addColumn("Proxima");
        tablaDatosDeconsulta.setModel(datosconsulta);
        cargarDatos();
    }//GEN-LAST:event_tablaConsultasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaConsultas;
    private javax.swing.JTable tablaDatosDeconsulta;
    // End of variables declaration//GEN-END:variables
}
