/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazProyectoMascotaFeliz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import proyectomascotafeliz.MantenimientosEnfermedad;
import proyectomascotafeliz.archivo;

/**
 *
 * @author Ronald
 */
public class Enfermedad extends javax.swing.JFrame {

    private archivo archivo = new archivo();
    MantenimientosEnfermedad conexion;//Se realiza una conexion a las enfermedades
    private DefaultTableModel enfermedades;//Se crea un nuevo modelo para la tabla enfermedades
    private JPanel panelInsertar;//Se crea un nuevo panel para insertar valores
    private String codigoguardar;//Se guarda el codigo de la enferemedad para poder cambiar la llave primaria

    /**
     * Creates new form Enfermedad
     */
    //Metodo constructor
    public Enfermedad() {
        archivo.leer();
        try {
            this.conexion = new MantenimientosEnfermedad(archivo.getBase(), archivo.getUser(), archivo.getPassword());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cargarEnfermedades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        insertarEnfermedad = new javax.swing.JButton();
        EliminarEnfermedad = new javax.swing.JButton();
        modificarenfermedad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEnfermedades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoenfermedad = new javax.swing.JTextField();
        NombreEnfermedad = new javax.swing.JTextField();
        CerrarVentana = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertarEnfermedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat.png"))); // NOI18N
        insertarEnfermedad.setBorderPainted(false);
        insertarEnfermedad.setContentAreaFilled(false);
        insertarEnfermedad.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat2.png"))); // NOI18N
        insertarEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarEnfermedadActionPerformed(evt);
            }
        });
        getContentPane().add(insertarEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        EliminarEnfermedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar.png"))); // NOI18N
        EliminarEnfermedad.setBorderPainted(false);
        EliminarEnfermedad.setContentAreaFilled(false);
        EliminarEnfermedad.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar2.png"))); // NOI18N
        EliminarEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEnfermedadActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        modificarenfermedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar.png"))); // NOI18N
        modificarenfermedad.setBorderPainted(false);
        modificarenfermedad.setContentAreaFilled(false);
        modificarenfermedad.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar2.png"))); // NOI18N
        modificarenfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarenfermedadActionPerformed(evt);
            }
        });
        getContentPane().add(modificarenfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        tablaEnfermedades.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tablaEnfermedades.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tablaEnfermedades.getTableHeader().setResizingAllowed(false);
        tablaEnfermedades.getTableHeader().setReorderingAllowed(false);
        tablaEnfermedades.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tablaEnfermedadesMouseWheelMoved(evt);
            }
        });
        tablaEnfermedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEnfermedadesMouseClicked(evt);
            }
        });
        tablaEnfermedades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaEnfermedadesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEnfermedades);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 460, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Enfermedad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        codigoenfermedad.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        codigoenfermedad.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(codigoenfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 99, -1));

        NombreEnfermedad.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        NombreEnfermedad.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(NombreEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 99, -1));

        CerrarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar.png"))); // NOI18N
        CerrarVentana.setBorderPainted(false);
        CerrarVentana.setContentAreaFilled(false);
        CerrarVentana.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar2.png"))); // NOI18N
        CerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarVentanaActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 370));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Enfermedad.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Enfermedad2.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Se cargan las enferemdades de la tabla enfermedad 

    public void cargarEnfermedades() {
        enfermedades = new DefaultTableModel();
        enfermedades.addColumn("Codigo");
        enfermedades.addColumn("Especies");
        ResultSet datos = conexion.select("*", "\"schProyecto\".\"enfermedad\"", "");
        try {
            while (datos.next()) {
                String[] valores = {datos.getString("cod_enfermedad"), datos.getString("nombre_enfermedad")};
                enfermedades.addRow(valores);
            }
            tablaEnfermedades.setModel(enfermedades);
            tablaEnfermedades.setOpaque(false);
        } catch (SQLException e) {

            System.out.println("Error: " + e.toString());
        }
    }

    //Se inserta una nueva enfermedad
    private void insertarEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarEnfermedadActionPerformed
        // TODO add your handling code here:
        panelInsertar = new JPanel();
        //Se crean y se asignan los componentes al panel insertar
        JButton insertar = new JButton("Insertar");
        JLabel codigo = new JLabel("Codigo");
        JLabel NombreEspecie = new JLabel("Nombre de Enfermedad");
        JTextField txtCodigo = new JTextField(10);
        JTextField txtNombreEspecie = new JTextField(10);
        panelInsertar.add(codigo);
        panelInsertar.add(txtCodigo);
        panelInsertar.add(NombreEspecie);
        panelInsertar.add(txtNombreEspecie);
        JOptionPane.showConfirmDialog(null, panelInsertar, "Insertar Enfermedad", JOptionPane.PLAIN_MESSAGE);
        String datos;
        String estado;
        datos = "('" + txtCodigo.getText() + "','" + txtNombreEspecie.getText() + "')";
        estado = conexion.Insertar("\"schProyecto\".\"enfermedad\"", datos);
        JOptionPane.showMessageDialog(null, "Datos insertado con exito");
        cargarEnfermedades();
    }//GEN-LAST:event_insertarEnfermedadActionPerformed
    //Se elimina una enfermedad de la tabla enfermedades
    private void EliminarEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEnfermedadActionPerformed
        // TODO add your handling code here:
        String estado;
        estado = this.conexion.eliminar("\"schProyecto\".\"enfermedad\"", String.valueOf(tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 0)));
        cargarEnfermedades();
        JOptionPane.showMessageDialog(null, "Datos eliminados");
        codigoenfermedad.setText("");
        NombreEnfermedad.setText("");
    }//GEN-LAST:event_EliminarEnfermedadActionPerformed
    //Se cierra la ventana enfermedad
    private void CerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarVentanaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CerrarVentanaActionPerformed
    //Se modifican los datos de la tabla enfermedad
    private void modificarenfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarenfermedadActionPerformed
        // TODO add your handling code here:
        String estado;

        estado = conexion.Modificar("\"schProyecto\".\"enfermedad\"", codigoenfermedad.getText(), NombreEnfermedad.getText(), codigoguardar);
        cargarEnfermedades();
        JOptionPane.showMessageDialog(null, "Datos modificados con exito");
    }//GEN-LAST:event_modificarenfermedadActionPerformed

    private void tablaEnfermedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEnfermedadesMouseClicked
        // TODO add your handling code here:
        codigoenfermedad.setText((String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 0));
        NombreEnfermedad.setText((String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 1));
        codigoguardar = (String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 0);
    }//GEN-LAST:event_tablaEnfermedadesMouseClicked

    private void tablaEnfermedadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaEnfermedadesKeyPressed
        // TODO add your handling code here:
        codigoenfermedad.setText((String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 0));
        NombreEnfermedad.setText((String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 1));
        codigoguardar = (String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 0);
    }//GEN-LAST:event_tablaEnfermedadesKeyPressed

    private void tablaEnfermedadesMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tablaEnfermedadesMouseWheelMoved
        // TODO add your handling code here:
        codigoenfermedad.setText((String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 0));
        NombreEnfermedad.setText((String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 1));
        codigoguardar = (String) tablaEnfermedades.getValueAt(tablaEnfermedades.getSelectedRow(), 0);
    }//GEN-LAST:event_tablaEnfermedadesMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enfermedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarVentana;
    private javax.swing.JButton EliminarEnfermedad;
    private javax.swing.JTextField NombreEnfermedad;
    private javax.swing.JTextField codigoenfermedad;
    private javax.swing.JButton insertarEnfermedad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarenfermedad;
    private javax.swing.JTable tablaEnfermedades;
    // End of variables declaration//GEN-END:variables
}
