/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.Mantenimientos.Especie;
import Interface.Mantenimientos.Raza;
import Interface.Procesos.Cita;
import Interface.Procesos.Consulta;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nestor
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() throws ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Mantenimientos = new javax.swing.JMenu();
        Especie = new javax.swing.JMenuItem();
        Raza = new javax.swing.JMenuItem();
        Dueño = new javax.swing.JMenuItem();
        Procesos = new javax.swing.JMenu();
        Cita = new javax.swing.JMenuItem();
        Consulta = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        VerConsultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mantenimientos.setText("Mantenimiento");

        Especie.setText("Especie");
        Especie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecieActionPerformed(evt);
            }
        });
        Mantenimientos.add(Especie);

        Raza.setText("Raza");
        Raza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RazaActionPerformed(evt);
            }
        });
        Mantenimientos.add(Raza);

        Dueño.setText("Dueño");
        Dueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueñoActionPerformed(evt);
            }
        });
        Mantenimientos.add(Dueño);

        jMenuBar1.add(Mantenimientos);

        Procesos.setText("Procesos");

        Cita.setText("Crear cita");
        Cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitaActionPerformed(evt);
            }
        });
        Procesos.add(Cita);

        Consulta.setText("Crear consulta");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });
        Procesos.add(Consulta);

        jMenuBar1.add(Procesos);

        Consultas.setText("Consultas");

        VerConsultas.setText("Ver consultas");
        Consultas.add(VerConsultas);

        jMenuBar1.add(Consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DueñoActionPerformed

    private void EspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecieActionPerformed
        // TODO add your handling code here:
        try{
        Especie especie = new Especie();
        setVisible(false);
        especie.setVisible(true);
        especie.llenarTablaEspecie();
        especie.llenarTxtEspecie();
        }catch(Exception e)
        {
            System.out.println("Error");
        }
        
    }//GEN-LAST:event_EspecieActionPerformed

    private void RazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RazaActionPerformed
        // TODO add your handling code here:
        try{
        Raza raza = new Raza();
        setVisible(false);
        raza.setVisible(true);
        raza.llenarTablaRaza();
        raza.llenarTxtRaza();
        }catch(Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_RazaActionPerformed

    private void CitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitaActionPerformed
        // TODO add your handling code here:
        try{
        Cita cita = new Cita();
        setVisible(false);
        cita.setVisible(true);
        }catch(Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_CitaActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
        // TODO add your handling code here:
        try{
        Consulta consulta = new Consulta();
        setVisible(false);
        consulta.setVisible(true);
        }catch(Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_ConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cita;
    private javax.swing.JMenuItem Consulta;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenuItem Dueño;
    private javax.swing.JMenuItem Especie;
    private javax.swing.JMenu Mantenimientos;
    private javax.swing.JMenu Procesos;
    private javax.swing.JMenuItem Raza;
    private javax.swing.JMenuItem VerConsultas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
