/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazProyectoMascotaFeliz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import proyectomascotafeliz.MantenimientoDueño;
import proyectomascotafeliz.archivo;

/**
 *
 * @author Ronald
 */
public class Dueño extends javax.swing.JFrame {

    private archivo archivo = new archivo();
    MantenimientoDueño conexion;
    private DefaultTableModel dueños;
    private JPanel panelInsertar;
    private String codigoguardar;

    /**
     * Creates new form Dueño
     */
    public Dueño() {
        archivo.leer();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        try {
            this.conexion = new MantenimientoDueño(archivo.getBase(), archivo.getUser(), archivo.getPassword());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        }
        cargarDueños();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        InsertarDueño = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ModificarDueño = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladueños = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        InsertarDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat.png"))); // NOI18N
        InsertarDueño.setBorderPainted(false);
        InsertarDueño.setContentAreaFilled(false);
        InsertarDueño.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat2.png"))); // NOI18N
        InsertarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarDueñoActionPerformed(evt);
            }
        });
        getContentPane().add(InsertarDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        ModificarDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar.png"))); // NOI18N
        ModificarDueño.setBorderPainted(false);
        ModificarDueño.setContentAreaFilled(false);
        ModificarDueño.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar2.png"))); // NOI18N
        ModificarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarDueñoActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        tabladueños.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tabladueños.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tabladueños.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladueñosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabladueñosMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tabladueños);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 521, 338));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Apellido1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Apellido2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Direccion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        Cedula.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        Cedula.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 95, -1));

        nombre.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        nombre.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 93, -1));

        apellido.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        apellido.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 93, -1));

        apellido2.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        apellido2.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 93, -1));

        telefono.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        telefono.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 93, -1));

        direccion.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        direccion.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 93, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 420));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Dueño.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Dueño2.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarDueñoActionPerformed
        // TODO add your handling code here:
        panelInsertar = new JPanel();
        JButton insertar = new JButton("Insertar");
        JLabel cedula = new JLabel("Cedula");
        JLabel nombre = new JLabel("Nombre");
        JLabel apellido1 = new JLabel("Apellido1");
        JLabel apellido2 = new JLabel("Apellido2");
        JLabel telefono = new JLabel("Telefono");
        JLabel direccion = new JLabel("Direccion");
        JTextField txtcedula = new JTextField(10);
        JTextField txtnombre = new JTextField(10);
        JTextField txtapellido1 = new JTextField(10);
        JTextField txtapellido2 = new JTextField(10);
        JTextField txttelefono = new JTextField(10);
        JTextField txtdireccion = new JTextField(10);
        panelInsertar.add(cedula);
        panelInsertar.add(txtcedula);
        panelInsertar.add(nombre);
        panelInsertar.add(txtnombre);
        panelInsertar.add(apellido1);
        panelInsertar.add(txtapellido1);

        panelInsertar.add(apellido2);
        panelInsertar.add(txtapellido2);
        panelInsertar.add(telefono);
        panelInsertar.add(txttelefono);
        panelInsertar.add(direccion);
        panelInsertar.add(txtdireccion);
        JOptionPane.showConfirmDialog(null, panelInsertar, "Insertar Dueño", JOptionPane.PLAIN_MESSAGE);
        String datos;
        String estado;
        datos = "('" + txtcedula.getText() + "','" + txtnombre.getText() + "','" + txtapellido1.getText()
                + "','" + txtapellido2.getText() + "','" + txttelefono.getText() + "','" + txtdireccion.getText() + "')";
        estado = conexion.Insertar("\"schProyecto\".\"dueno\"", datos);
        JOptionPane.showMessageDialog(null, "Datos insertado con exito");
        cargarDueños();
    }//GEN-LAST:event_InsertarDueñoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String estado;

        estado = this.conexion.eliminar("\"schProyecto\".\"dueno\"", String.valueOf(tabladueños.getValueAt(tabladueños.getSelectedRow(), 0)));
        cargarDueños();
        JOptionPane.showMessageDialog(null, "Datos eliminados");
        Cedula.setText("");
        nombre.setText("");
        apellido.setText("");
        apellido2.setText("");
        telefono.setText("");
        direccion.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabladueñosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladueñosMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_tabladueñosMouseExited

    private void tabladueñosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladueñosMouseClicked
        // TODO add your handling code here:
        Cedula.setText((String) tabladueños.getValueAt(tabladueños.getSelectedRow(), 0));
        nombre.setText((String) tabladueños.getValueAt(tabladueños.getSelectedRow(), 1));
        apellido.setText((String) tabladueños.getValueAt(tabladueños.getSelectedRow(), 2));
        apellido2.setText((String) tabladueños.getValueAt(tabladueños.getSelectedRow(), 3));
        telefono.setText((String) tabladueños.getValueAt(tabladueños.getSelectedRow(), 4));
        direccion.setText((String) tabladueños.getValueAt(tabladueños.getSelectedRow(), 5));
        codigoguardar = (String) tabladueños.getValueAt(tabladueños.getSelectedRow(), 0);
    }//GEN-LAST:event_tabladueñosMouseClicked

    private void ModificarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarDueñoActionPerformed
        // TODO add your handling code here:
        String estado;

        estado = conexion.Modificar("\"schProyecto\".\"dueno\"", Cedula.getText(), nombre.getText(), apellido.getText(),
                apellido2.getText(), telefono.getText(), direccion.getText(), codigoguardar);
        cargarDueños();
        JOptionPane.showMessageDialog(null, "Datos modificados con exito");

        Cedula.setText("");
        nombre.setText("");
        apellido.setText("");
        apellido2.setText("");
        telefono.setText("");
        direccion.setText("");
    }//GEN-LAST:event_ModificarDueñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dueño().setVisible(true);
            }
        });
    }

    public void cargarDueños() {
        dueños = new DefaultTableModel();
        dueños.addColumn("Cedula");
        dueños.addColumn("Nombre");
        dueños.addColumn("Apellido1");
        dueños.addColumn("Apellido2");
        dueños.addColumn("Telfono");
        dueños.addColumn("Direccion");
        ResultSet datos = conexion.select("*", "\"schProyecto\".\"dueno\"", "");
        try {

            while (datos.next()) {
                String[] valores = {datos.getString("cedula"), datos.getString("nombre"), datos.getString("apellido1"),
                     datos.getString("apellido2"), datos.getString("telefono"), datos.getString("direccion")};
                dueños.addRow(valores);
            }
            tabladueños.setModel(dueños);

        } catch (Exception e) {

            System.out.println("Error: " + e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cedula;
    private javax.swing.JButton InsertarDueño;
    private javax.swing.JButton ModificarDueño;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField apellido2;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabladueños;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
