/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazProyectoMascotaFeliz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import proyectomascotafeliz.Mantenimientoespecies;
import proyectomascotafeliz.archivo;

/**
 *
 * @author Ronald
 */
public class Especie extends javax.swing.JFrame {

    private archivo archivo = new archivo();
    Mantenimientoespecies conexion;//Variable conexion para conectarse a la base de datos
    private DefaultTableModel especies;//Modelo de tabla de especies
    private JPanel panelInsertar;//Nuevo panel para insertar los datos
    private String codigoguardar;//sirve para almacenar el codigo de la especie

    /**
     * Creates new form Especie
     */
    //Metodo constructor
    public Especie() {
        archivo.leer();
        try {
            this.conexion = new Mantenimientoespecies(archivo.getBase(), archivo.getUser(), archivo.getPassword());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cargarespecies();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaespecies = new javax.swing.JTable();
        InsertarEspecie = new javax.swing.JButton();
        Eliminarespecie = new javax.swing.JButton();
        modificarespecie = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        especie = new javax.swing.JTextField();
        Cerrarventanespecie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaespecies.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 0)));
        tablaespecies.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tablaespecies.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tablaespecies.getTableHeader().setResizingAllowed(false);
        tablaespecies.getTableHeader().setReorderingAllowed(false);
        tablaespecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaespeciesMouseClicked(evt);
            }
        });
        tablaespecies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaespeciesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaespecies);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 470, 390));

        InsertarEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat.png"))); // NOI18N
        InsertarEspecie.setBorderPainted(false);
        InsertarEspecie.setContentAreaFilled(false);
        InsertarEspecie.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat2.png"))); // NOI18N
        InsertarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarEspecieActionPerformed(evt);
            }
        });
        getContentPane().add(InsertarEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 60));

        Eliminarespecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar.png"))); // NOI18N
        Eliminarespecie.setBorderPainted(false);
        Eliminarespecie.setContentAreaFilled(false);
        Eliminarespecie.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar2.png"))); // NOI18N
        Eliminarespecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarespecieActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminarespecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, 60));

        modificarespecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar.png"))); // NOI18N
        modificarespecie.setBorderPainted(false);
        modificarespecie.setContentAreaFilled(false);
        modificarespecie.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar2.png"))); // NOI18N
        modificarespecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarespecieActionPerformed(evt);
            }
        });
        getContentPane().add(modificarespecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 150, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Codigo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Especie");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 90, 40));

        codigo.setBackground(new java.awt.Color(240, 240, 240));
        codigo.setCaretColor(new java.awt.Color(153, 51, 0));
        codigo.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        codigo.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 100, 30));

        especie.setBackground(new java.awt.Color(240, 240, 240));
        especie.setCaretColor(new java.awt.Color(153, 0, 0));
        especie.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        especie.setSelectionColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 100, 30));

        Cerrarventanespecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar.png"))); // NOI18N
        Cerrarventanespecie.setBorderPainted(false);
        Cerrarventanespecie.setContentAreaFilled(false);
        Cerrarventanespecie.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar2.png"))); // NOI18N
        Cerrarventanespecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarventanespecieActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrarventanespecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 511, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/fondo-madera-negro.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 460));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Especie.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Especie2.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Accion del botoon insertar
    private void InsertarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarEspecieActionPerformed
        // TODO add your handling code here:
        panelInsertar = new JPanel();//Se crea el panel insertar
        //Se le asigna al panel los componentes
        JButton insertar = new JButton("Insertar");
        JLabel codigo = new JLabel("Codigo");
        JLabel NombreEspecie = new JLabel("Nombre de Especie");
        JTextField txtCodigo = new JTextField(10);
        JTextField txtNombreEspecie = new JTextField(10);
        panelInsertar.add(codigo);
        panelInsertar.add(txtCodigo);
        panelInsertar.add(NombreEspecie);
        panelInsertar.add(txtNombreEspecie);
        //Se imprime el panael
        JOptionPane.showConfirmDialog(null, panelInsertar, "Insertar Especie", JOptionPane.PLAIN_MESSAGE);
        String datos;
        String estado;
        //Se inserta la nueva especie
        datos = "('" + txtCodigo.getText() + "','" + txtNombreEspecie.getText() + "')";
        estado = conexion.Insertar("\"schProyecto\".\"especie\"", datos);
        JOptionPane.showMessageDialog(null, "Datos insertado con exito");
        cargarespecies();
    }//GEN-LAST:event_InsertarEspecieActionPerformed
    //Accion boton eliminar
    private void EliminarespecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarespecieActionPerformed
        // TODO add your handling code here:
        String estado;
        //Se elimina el dato seleccionado en la tabla tablaespecies
        estado = this.conexion.eliminar("\"schProyecto\".\"especie\"", String.valueOf(tablaespecies.getValueAt(tablaespecies.getSelectedRow(), 0)));
        cargarespecies();
        JOptionPane.showMessageDialog(null, "Datos eliminados");
        codigo.setText("");
        especie.setText("");

    }//GEN-LAST:event_EliminarespecieActionPerformed
    //Se le assigna valores a las cajas de texto 
    private void tablaespeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaespeciesMouseClicked
        // TODO add your handling code here:
        codigo.setText((String) tablaespecies.getValueAt(tablaespecies.getSelectedRow(), 0));
        especie.setText((String) tablaespecies.getValueAt(tablaespecies.getSelectedRow(), 1));
        codigoguardar = (String) tablaespecies.getValueAt(tablaespecies.getSelectedRow(), 0);

    }//GEN-LAST:event_tablaespeciesMouseClicked
    //Se cierra la ventana
    private void CerrarventanespecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarventanespecieActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CerrarventanespecieActionPerformed
    //Accion Boton Modificar
    private void modificarespecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarespecieActionPerformed
        // TODO add your handling code here:
        String estado;
        //Se modifica la especie seleccionada
        estado = conexion.Modificar("\"schProyecto\".\"especie\"", codigo.getText(), especie.getText(), codigoguardar);
        cargarespecies();
        JOptionPane.showMessageDialog(null, "Datos modificados con exito");

        codigo.setText("");
        especie.setText("");

    }//GEN-LAST:event_modificarespecieActionPerformed
    //Se le asigna los valores a las cajas de texto al mover las teclas arriba y abajo
    private void tablaespeciesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaespeciesKeyPressed
        // TODO add your handling code here:
        codigo.setText((String) tablaespecies.getValueAt(tablaespecies.getSelectedRow(), 0));
        especie.setText((String) tablaespecies.getValueAt(tablaespecies.getSelectedRow(), 1));
        codigoguardar = (String) tablaespecies.getValueAt(tablaespecies.getSelectedRow(), 0);
    }//GEN-LAST:event_tablaespeciesKeyPressed
    //Se cargan las especies de la tabla especies de la base de datos  
    public void cargarespecies() {
        especies = new DefaultTableModel();
        especies.addColumn("Codigo");
        especies.addColumn("Especies");
        ResultSet datos = conexion.select("*", "\"schProyecto\".\"especie\"", "");

        try {

            while (datos.next()) {
                String[] valores = {datos.getString("cod_especie"), datos.getString("nombre_especie")};
                especies.addRow(valores);
            }

            tablaespecies.setModel(especies);
            tablaespecies.setOpaque(false);

        } catch (Exception e) {

            System.out.println("Error: " + e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Especie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Especie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Especie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Especie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Especie().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrarventanespecie;
    private javax.swing.JButton Eliminarespecie;
    private javax.swing.JButton InsertarEspecie;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField especie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarespecie;
    private javax.swing.JTable tablaespecies;
    // End of variables declaration//GEN-END:variables
}
