/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazProyectoMascotaFeliz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import proyectomascotafeliz.archivo;
import proyectomascotafeliz.mantenimientoVacunas;

/**
 *
 * @author Ronald
 */
public class Vacuna extends javax.swing.JFrame {

    private archivo archivo = new archivo();
    mantenimientoVacunas conexion;//Se crea una conexion a vacunas
    DefaultTableModel vacunas;//Se crea una modelo para la tabla vacunas
    JPanel panelInsertar;//Se crea un panel para insertar una vacuna
    String codigoguardar = "";//Se guarda el codigo de la vacuna para cambiar la llave primaria

    /**
     * Creates new form Vacuna
     */
    //Metodo constructor
    public Vacuna() {
        archivo.leer();
        try {
            this.conexion = new mantenimientoVacunas(archivo.getBase(), archivo.getUser(), archivo.getPassword());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Especie.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cargarVacunas();
    }

    //Se cargan las vacunas de la tabla vacunas de la base de datos 
    public void cargarVacunas() {
        vacunas = new DefaultTableModel();
        vacunas.addColumn("Codigo");
        vacunas.addColumn("Nombre");
        ResultSet datos = conexion.select("*", "\"schProyecto\".\"vacuna\"", "");
        try {
            while (datos.next()) {
                String[] valores = {datos.getString("cod_vacuna"), datos.getString("nombre_vacuna")};
                vacunas.addRow(valores);
            }
            tablaVacunas.setModel(vacunas);
            tablaVacunas.setOpaque(false);
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertarVacuna = new javax.swing.JButton();
        EliminarVacuna = new javax.swing.JButton();
        ModificarVacuna = new javax.swing.JButton();
        CerrarVentana = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVacunas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        NombreVacuna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertarVacuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat.png"))); // NOI18N
        InsertarVacuna.setBorderPainted(false);
        InsertarVacuna.setContentAreaFilled(false);
        InsertarVacuna.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Insertat2.png"))); // NOI18N
        InsertarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarVacunaActionPerformed(evt);
            }
        });
        getContentPane().add(InsertarVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 50));

        EliminarVacuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar.png"))); // NOI18N
        EliminarVacuna.setBorderPainted(false);
        EliminarVacuna.setContentAreaFilled(false);
        EliminarVacuna.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Eliminar2.png"))); // NOI18N
        EliminarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVacunaActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, -1));

        ModificarVacuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar.png"))); // NOI18N
        ModificarVacuna.setBorderPainted(false);
        ModificarVacuna.setContentAreaFilled(false);
        ModificarVacuna.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Modificar2.png"))); // NOI18N
        ModificarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVacunaActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        CerrarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar.png"))); // NOI18N
        CerrarVentana.setBorderPainted(false);
        CerrarVentana.setContentAreaFilled(false);
        CerrarVentana.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Cerrar2.png"))); // NOI18N
        CerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarVentanaActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 140, -1));

        tablaVacunas.setSelectionBackground(new java.awt.Color(102, 0, 0));
        tablaVacunas.getTableHeader().setResizingAllowed(false);
        tablaVacunas.getTableHeader().setReorderingAllowed(false);
        tablaVacunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVacunasMouseClicked(evt);
            }
        });
        tablaVacunas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaVacunasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVacunas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 442, 363));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nombre Vacuna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 120, -1));
        getContentPane().add(NombreVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 450));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Vacuna.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseños/Dueño/Vacuna2.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Se cierra la ventana
    private void CerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarVentanaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CerrarVentanaActionPerformed
    //Se inserta una nueva vacuna
    private void InsertarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarVacunaActionPerformed
        // TODO add your handling code here:
        panelInsertar = new JPanel();
        //Se crean y asignan los componentes al panal para insertar
        JButton insertar = new JButton("Insertar");
        JLabel codigo = new JLabel("Codigo");
        JLabel NombreVacuna = new JLabel("Nombre de Vacuna");
        JTextField txtCodigo = new JTextField(10);
        JTextField txtVacuna = new JTextField(10);
        panelInsertar.add(codigo);
        panelInsertar.add(txtCodigo);
        panelInsertar.add(NombreVacuna);
        panelInsertar.add(txtVacuna);
        JOptionPane.showConfirmDialog(null, panelInsertar, "Insertar Vacuna", JOptionPane.PLAIN_MESSAGE);
        String datos;
        String estado;
        //Se insertar los datos de las vacunas en la base de datos
        datos = "('" + txtCodigo.getText() + "','" + txtVacuna.getText() + "')";
        estado = conexion.Insertar("\"schProyecto\".\"vacuna\"", datos);
        cargarVacunas();
        JOptionPane.showMessageDialog(null, "Datos insertado con exito");
    }//GEN-LAST:event_InsertarVacunaActionPerformed

    private void EliminarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVacunaActionPerformed
        // TODO add your handling code here:
        String estado;

        estado = this.conexion.eliminar("\"schProyecto\".\"vacuna\"", String.valueOf(tablaVacunas.getValueAt(tablaVacunas.getSelectedRow(), 0)));
        cargarVacunas();
        JOptionPane.showMessageDialog(null, "Datos eliminados");
        Codigo.setText("");
        NombreVacuna.setText("");
    }//GEN-LAST:event_EliminarVacunaActionPerformed
    //Se le asignan valores a las cajas de texto 
    private void tablaVacunasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVacunasMouseClicked
        // TODO add your handling code here:
        Codigo.setText((String) tablaVacunas.getValueAt(tablaVacunas.getSelectedRow(), 0));
        NombreVacuna.setText((String) tablaVacunas.getValueAt(tablaVacunas.getSelectedRow(), 1));
        codigoguardar = (String) tablaVacunas.getValueAt(tablaVacunas.getSelectedRow(), 0);
    }//GEN-LAST:event_tablaVacunasMouseClicked
    //Se modifican las vacunas von base a  los valores digitados en las cajas de texto
    private void ModificarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVacunaActionPerformed
        // TODO add your handling code here:
        String estado;

        estado = conexion.Modificar("\"schProyecto\".\"vacuna\"", Codigo.getText(), NombreVacuna.getText(), codigoguardar);
        cargarVacunas();
        JOptionPane.showMessageDialog(null, "Datos modificados con exito");

        Codigo.setText("");
        NombreVacuna.setText("");
    }//GEN-LAST:event_ModificarVacunaActionPerformed

    private void tablaVacunasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaVacunasKeyPressed
        // TODO add your handling code here:
        Codigo.setText((String) tablaVacunas.getValueAt(tablaVacunas.getSelectedRow(), 0));
        NombreVacuna.setText((String) tablaVacunas.getValueAt(tablaVacunas.getSelectedRow(), 1));
        codigoguardar = (String) tablaVacunas.getValueAt(tablaVacunas.getSelectedRow(), 0);
    }//GEN-LAST:event_tablaVacunasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vacuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarVentana;
    private javax.swing.JTextField Codigo;
    private javax.swing.JButton EliminarVacuna;
    private javax.swing.JButton InsertarVacuna;
    private javax.swing.JButton ModificarVacuna;
    private javax.swing.JTextField NombreVacuna;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVacunas;
    // End of variables declaration//GEN-END:variables
}
